console.log("Welcome to the JS!")

console.log(document.querySelector('.heyo'))

let heyoDiv = document.querySelector('.heyo')

heyoDiv.textcontent = 'Welcome to the Jungle! This message was generated by my JS code! We also have fun and games.'



const femaleCharacters = people.filter(person === person.gender === "female")
console.log(femaleCharacters)

const otherCharacters = people.filter(person => person.gender === "n/a" || person.gender === "none" || person.gender === "hermaphrodite")
console.log(otherCharacters)


let maleButton = document.querySelector('#maleButton')
let femalButton = document.querySelector('#femaleButton')
let otherButton = document.querySelector('#otherButton')

maleButton.addEventListener("click", function( event ) {
    console.log('Thanks for clicking!')

} )

let counter = 1

function populateDOM (characters) {
    characters.forEach(person => {
        let nameItem=document.createElement("li")
        nameItem.textContent = person.nameItem
        castList.appendChild(nameItem) 

    })



}